version: '3.7'

services:
  db:
    restart: always

    image: postgres:12.0-alpine
    container_name: flight_optimizer_postgres
    environment:
      - POSTGRES_DB=flight_optimizer_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin


  django:
    build: .
    container_name: flight_optimizer_django
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*
      - DATABASE_URL=postgres://admin:admin@flight_optimizer_postgres:5432/flight_optimizer_db
      - SECRET_KEY=secret
    command: /app/manage.py runserver 0.0.0.0:5000